source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
    hide_cursor = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 0
}

animations {
    enabled = true
    bezier = apple, 0.25, 0.1, 0.25, 1
    animation = fadeIn,  1, 3, apple
    animation = fadeOut, 1, 6, apple
}

# Time — like Hyadum: "16:30"
label {
    monitor =
    text = $TIME
    font_size = 75
    font_family = Gunplay
    color = rgb(F9F9F9)
    position = 0, 55
    halign = center
    valign = center
}

# Password — invisible total
input-field {
    monitor =
    size = 1, 1
    position = 0, -50
    halign = center
    valign = bottom

    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    font_family = Sans
    font_color = rgba(0, 0, 0, 0)
    dots_size = 0
    placeholder_text =
    check_text =
    fail_text =
    fade_on_empty = true
    fade_timeout = 0
    rounding = 0
    shadow_passes = 0
}

auth {
    fingerprint:enabled = false
}

source = ~/.local/state/omarchy/toggles/hyprlock.conf
