local theme = {
  bg = "#121212",
  fg = "#bebebe",
  accent = "#808080",
  selection = "#808080",
  comment = "#525252",
  cursor = "#eaeaea",
  line = "#1a1a1a",
  visual = "#2a2a2a",
  error = "#7c7c7c",
  warning = "#a0a0a0",
  info = "#808080",
  hint = "#868686",
}

return {
  Normal = { fg = theme.fg, bg = theme.bg },
  NormalFloat = { fg = theme.fg, bg = theme.bg },
  Comment = { fg = theme.comment, italic = true },
  Cursor = { fg = theme.bg, bg = theme.cursor },
  CursorLine = { bg = theme.line },
  CursorLineNr = { fg = theme.accent },
  LineNr = { fg = theme.comment },
  Visual = { bg = theme.visual },
  Search = { fg = theme.bg, bg = theme.accent },
  IncSearch = { fg = theme.bg, bg = theme.accent },
  Pmenu = { fg = theme.fg, bg = theme.bg },
  PmenuSel = { fg = theme.bg, bg = theme.accent },
  PmenuSbar = { bg = theme.line },
  PmenuThumb = { bg = theme.comment },
  StatusLine = { fg = theme.fg, bg = theme.line },
  StatusLineNC = { fg = theme.comment, bg = theme.bg },
  TabLine = { fg = theme.comment, bg = theme.bg },
  TabLineSel = { fg = theme.fg, bg = theme.accent },
  TabLineFill = { bg = theme.bg },
  Boolean = { fg = theme.accent },
  Character = { fg = theme.accent },
  Constant = { fg = theme.accent },
  Debug = { fg = theme.accent },
  Define = { fg = theme.accent },
  Delimiter = { fg = theme.fg },
  Error = { fg = theme.error },
  ErrorMsg = { fg = theme.error },
  Exception = { fg = theme.accent },
  Float = { fg = theme.accent },
  Function = { fg = theme.fg },
  Identifier = { fg = theme.fg },
  Keyword = { fg = theme.accent },
  Label = { fg = theme.accent },
  Macro = { fg = theme.accent },
  Number = { fg = theme.accent },
  Operator = { fg = theme.accent },
  PreProc = { fg = theme.accent },
  Repeat = { fg = theme.accent },
  Special = { fg = theme.accent },
  SpecialChar = { fg = theme.accent },
  SpecialComment = { fg = theme.comment },
  Statement = { fg = theme.accent },
  StorageClass = { fg = theme.accent },
  String = { fg = theme.fg },
  Structure = { fg = theme.accent },
  Tag = { fg = theme.accent },
  Title = { fg = theme.accent },
  Todo = { fg = theme.bg, bg = theme.warning },
  Type = { fg = theme.accent },
  Typedef = { fg = theme.accent },
  Underlined = { underline = true },
  VertSplit = { fg = theme.comment, bg = theme.bg },
  WarningMsg = { fg = theme.warning },
  Whitespace = { fg = theme.comment },
  NonText = { fg = theme.comment },
  EndOfBuffer = { fg = theme.bg },
  TSAnnotation = { fg = theme.accent },
  TSAttribute = { fg = theme.accent },
  TSBoolean = { fg = theme.accent },
  TSCharacter = { fg = theme.accent },
  TSComment = { fg = theme.comment, italic = true },
  TSConditional = { fg = theme.accent },
  TSConstant = { fg = theme.accent },
  TSConstBuiltin = { fg = theme.accent },
  TSConstMacro = { fg = theme.accent },
  TSConstructor = { fg = theme.fg },
  TSError = { fg = theme.error },
  TSException = { fg = theme.accent },
  TSField = { fg = theme.fg },
  TSFloat = { fg = theme.accent },
  TSFunction = { fg = theme.fg },
  TSFunctionBuiltin = { fg = theme.accent },
  TSInclude = { fg = theme.accent },
  TSKeyword = { fg = theme.accent },
  TSKeywordFunction = { fg = theme.accent },
  TSKeywordOperator = { fg = theme.accent },
  TSLabel = { fg = theme.accent },
  TSMethod = { fg = theme.fg },
  TSNamespace = { fg = theme.accent },
  TSNumber = { fg = theme.accent },
  TSOperator = { fg = theme.accent },
  TSParameter = { fg = theme.fg },
  TSParameterReference = { fg = theme.fg },
  TSProperty = { fg = theme.fg },
  TSPunctDelimiter = { fg = theme.fg },
  TSPunctBracket = { fg = theme.fg },
  TSPunctSpecial = { fg = theme.accent },
  TSRepeat = { fg = theme.accent },
  TSString = { fg = theme.fg },
  TSStringEscape = { fg = theme.accent },
  TSStringRegex = { fg = theme.accent },
  TSStringSpecial = { fg = theme.accent },
  TSSymbol = { fg = theme.accent },
  TSTag = { fg = theme.accent },
  TSTagDelimiter = { fg = theme.comment },
  TSText = { fg = theme.fg },
  TSStrong = { bold = true },
  TSEmphasis = { italic = true },
  TSUnderline = { underline = true },
  TSStrike = { strikethrough = true },
  TSTitle = { fg = theme.accent },
  TSLiteral = { fg = theme.fg },
  TSURI = { fg = theme.accent, underline = true },
  TSVariable = { fg = theme.fg },
  TSVariableBuiltin = { fg = theme.accent },
  TSType = { fg = theme.accent },
  TSTypeBuiltin = { fg = theme.accent },
}
